// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/social-network.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "socialnetwork";

/** ===== MESSAGES ===== */
export enum FriendStatus {
  PENDING = 0,
  ACCEPTED = 1,
  BLOCKED = 2,
  UNRECOGNIZED = -1,
}

export interface RelationFriendInfo {
  relationId: number;
  friendId: number;
  friendRealname: string;
  avatarUrl: string;
  status: FriendStatus;
  create_at: string;
}

export interface FriendInfo {
  friendId: number;
  friendRealname: string;
  avatarUrl: string;
  status: FriendStatus;
}

export interface AddFriendRequest {
  userId: number;
  friendId: number;
}

export interface AddFriendResponse {
  relationId: number;
  userId: number;
  friendId: number;
  status: FriendStatus;
  create_at: string;
}

export interface GetSentFriendRequest {
  userId: number;
}

export interface GetSentFriendResponse {
  relationFriendInfo: RelationFriendInfo[];
}

export interface GetIncomingFriendRequest {
  userId: number;
}

export interface GetIncomingFriendResponse {
  relationFriendInfo: RelationFriendInfo[];
}

export interface AcceptFriendRequest {
  relationId: number;
  userId: number;
}

export interface AcceptFriendResponse {
  relationFriendInfo: RelationFriendInfo | undefined;
}

export interface RejectFriendRequest {
  relationId: number;
  userId: number;
}

export interface RejectFriendResponse {
  success: boolean;
}

export interface GetAllFriendRequest {
  userId: number;
}

export interface GetAllFriendResponse {
  friendInfo: FriendInfo[];
}

export interface UnfriendRequest {
  userId: number;
  friendId: number;
}

export interface UnfriendResponse {
  success: boolean;
}

export interface BlockUserRequest {
  userId: number;
  friendId: number;
}

export interface BlockUserResponse {
  success: boolean;
}

export interface CanChatRequest {
  userId: number;
  friendId: number;
}

export interface CanChatResponse {
  canChat: boolean;
}

export interface Message {
  roomId: string;
  userId: number;
  friendId: number;
  content: string;
  create_at: string;
}

export interface SaveMessageRequest {
  message: Message | undefined;
}

export interface SaveMessageResponse {
  success: boolean;
}

export interface GetMessageRequest {
  userId: number;
  roomId: string;
}

export interface GetMessageResponse {
  message: Message[];
}

export const SOCIALNETWORK_PACKAGE_NAME = "socialnetwork";

/** ===== SERVICE DEFINITION ===== */

export interface SocialNetworkServiceClient {
  /** Gửi lời mời kết bạn ( Người gửi ) */

  addFriend(request: AddFriendRequest, metadata?: Metadata): Observable<AddFriendResponse>;

  /** Xem tất cả lời mời kết bạn mà bản thân đã gửi ( Người gửi ) */

  getSentFriend(request: GetSentFriendRequest, metadata?: Metadata): Observable<GetSentFriendResponse>;

  /** Xem tất cả lời mời kết bạn của bản thân để accept ( Người nhận ) */

  getIncomingFriend(request: GetIncomingFriendRequest, metadata?: Metadata): Observable<GetIncomingFriendResponse>;

  /** Chấp nhận yêu cầu kết bạn ( Người nhận ) */

  acceptFriend(request: AcceptFriendRequest, metadata?: Metadata): Observable<AcceptFriendResponse>;

  /** Hủy yêu cầu kết bạn ( chỉ áp dụng khi pending ) ( xóa record ) ( Người nhận ) */

  rejectFriend(request: RejectFriendRequest, metadata?: Metadata): Observable<RejectFriendResponse>;

  /** Lấy danh sách bạn bè của bản thân */

  getAllFriend(request: GetAllFriendRequest, metadata?: Metadata): Observable<GetAllFriendResponse>;

  /** Xóa 1 bạn bè nhất định ( xóa record ) */

  unfriend(request: UnfriendRequest, metadata?: Metadata): Observable<UnfriendResponse>;

  /** Chặn bạn bè bất kì ( Blocking User ) */

  blockUser(request: BlockUserRequest, metadata?: Metadata): Observable<BlockUserResponse>;

  /** Xem bạn và 1 user bất kì có phải bạn bè hay không */

  canChat(request: CanChatRequest, metadata?: Metadata): Observable<CanChatResponse>;

  /** Lưu tin nhắn chat giữa 2 người */

  saveMessage(request: SaveMessageRequest, metadata?: Metadata): Observable<SaveMessageResponse>;

  /** Lấy lịch sử nhắn tin của 2 người */

  getMessage(request: GetMessageRequest, metadata?: Metadata): Observable<GetMessageResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface SocialNetworkServiceController {
  /** Gửi lời mời kết bạn ( Người gửi ) */

  addFriend(request: AddFriendRequest, metadata?: Metadata): Observable<AddFriendResponse>;

  /** Xem tất cả lời mời kết bạn mà bản thân đã gửi ( Người gửi ) */

  getSentFriend(request: GetSentFriendRequest, metadata?: Metadata): Observable<GetSentFriendResponse>;

  /** Xem tất cả lời mời kết bạn của bản thân để accept ( Người nhận ) */

  getIncomingFriend(request: GetIncomingFriendRequest, metadata?: Metadata): Observable<GetIncomingFriendResponse>;

  /** Chấp nhận yêu cầu kết bạn ( Người nhận ) */

  acceptFriend(request: AcceptFriendRequest, metadata?: Metadata): Observable<AcceptFriendResponse>;

  /** Hủy yêu cầu kết bạn ( chỉ áp dụng khi pending ) ( xóa record ) ( Người nhận ) */

  rejectFriend(request: RejectFriendRequest, metadata?: Metadata): Observable<RejectFriendResponse>;

  /** Lấy danh sách bạn bè của bản thân */

  getAllFriend(request: GetAllFriendRequest, metadata?: Metadata): Observable<GetAllFriendResponse>;

  /** Xóa 1 bạn bè nhất định ( xóa record ) */

  unfriend(request: UnfriendRequest, metadata?: Metadata): Observable<UnfriendResponse>;

  /** Chặn bạn bè bất kì ( Blocking User ) */

  blockUser(request: BlockUserRequest, metadata?: Metadata): Observable<BlockUserResponse>;

  /** Xem bạn và 1 user bất kì có phải bạn bè hay không */

  canChat(request: CanChatRequest, metadata?: Metadata): Observable<CanChatResponse>;

  /** Lưu tin nhắn chat giữa 2 người */

  saveMessage(request: SaveMessageRequest, metadata?: Metadata): Observable<SaveMessageResponse>;

  /** Lấy lịch sử nhắn tin của 2 người */

  getMessage(request: GetMessageRequest, metadata?: Metadata): Observable<GetMessageResponse>;
}

export function SocialNetworkServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "addFriend",
      "getSentFriend",
      "getIncomingFriend",
      "acceptFriend",
      "rejectFriend",
      "getAllFriend",
      "unfriend",
      "blockUser",
      "canChat",
      "saveMessage",
      "getMessage",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SocialNetworkService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SocialNetworkService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SOCIAL_NETWORK_SERVICE_NAME = "SocialNetworkService";
