// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/social-network.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "socialnetwork";

/** ===== MESSAGES ===== */
export enum FriendStatus {
  PENDING = 0,
  ACCEPTED = 1,
  BLOCKED = 2,
  UNRECOGNIZED = -1,
}

export enum role {
  ADMIN = 0,
  MEMBER = 1,
  UNRECOGNIZED = -1,
}

export interface RelationFriendInfo {
  relationId: number;
  friendId: number;
  friendRealname: string;
  avatarUrl: string;
  status: FriendStatus;
  create_at: string;
}

export interface FriendInfo {
  friendId: number;
  friendRealname: string;
  avatarUrl: string;
  status: FriendStatus;
}

export interface AddFriendRequest {
  userId: number;
  friendId: number;
}

export interface AddFriendResponse {
  relationId: number;
  userId: number;
  friendId: number;
  status: FriendStatus;
  create_at: string;
}

export interface GetSentFriendRequest {
  userId: number;
}

export interface GetSentFriendResponse {
  relationFriendInfo: RelationFriendInfo[];
}

export interface GetIncomingFriendRequest {
  userId: number;
}

export interface GetIncomingFriendResponse {
  relationFriendInfo: RelationFriendInfo[];
}

export interface AcceptFriendRequest {
  relationId: number;
  userId: number;
}

export interface AcceptFriendResponse {
  relationFriendInfo: RelationFriendInfo | undefined;
}

export interface RejectFriendRequest {
  relationId: number;
  userId: number;
}

export interface RejectFriendResponse {
  success: boolean;
}

export interface GetAllFriendRequest {
  userId: number;
}

export interface GetAllFriendResponse {
  friendInfo: FriendInfo[];
}

export interface UnfriendRequest {
  userId: number;
  friendId: number;
}

export interface UnfriendResponse {
  success: boolean;
}

export interface BlockUserRequest {
  userId: number;
  friendId: number;
}

export interface BlockUserResponse {
  success: boolean;
}

export interface CanChatRequest {
  userId: number;
  friendId: number;
}

export interface CanChatResponse {
  canChat: boolean;
}

export interface Message {
  roomId: string;
  userId: number;
  content: string;
  create_at: string;
}

export interface MessageTraVe {
  roomId: string;
  userId: number;
  avatarUrl: string;
  realname: string;
  content: string;
  create_at: string;
}

export interface SaveMessageRequest {
  message: Message | undefined;
}

export interface SaveMessageResponse {
  success: boolean;
}

export interface GetMessageRequest {
  userId: number;
  roomId: string;
}

export interface GetMessageResponse {
  message: MessageTraVe[];
}

export interface CreateGroupRequest {
  name: string;
  avatarUrl: string;
  description: string;
  ownerId: number;
  maxMember: number;
  userId: number[];
}

export interface CreateGroupResponse {
  success: boolean;
}

export interface AddUserToGroupRequest {
  userId: number;
  groupId: number;
  role: number;
}

export interface AddUserToGroupResponse {
  success: boolean;
}

export interface CheckGroupUserRequest {
  userId: number;
  groupId: number;
}

export interface CheckGroupUserResponse {
  success: boolean;
}

export interface GetAllGroupRequest {
  userId: number;
}

export interface GroupInfo {
  groupId: number;
  name: string;
  avatarUrl: string;
  description: string;
  ownerId: number;
}

export interface GetAllGroupResponse {
  groupInfo: GroupInfo[];
}

export interface GetAllCommentRequest {
  postId: number;
  userId: number;
}

export interface UpdateCommentRequest {
  commentId: number;
  userId: number;
  content: string;
}

export interface UpdateCommentResponse {
  success: boolean;
}

export interface DeleteCommentRequest {
  commentId: number;
  userId: number;
}

export interface DeleteCommentResponse {
  success: boolean;
}

export interface LikeCommentRequest {
  commentId: number;
  userId: number;
}

export interface LikeCommentResponse {
  success: boolean;
}

export interface UnlikeCommentRequest {
  commentId: number;
  userId: number;
}

export interface UnlikeCommentResponse {
  success: boolean;
}

export interface GetAllCommentResponse {
  comments: CommentNode[];
}

export interface CommentNode {
  id: number;
  postId: number;
  parentId: number;
  userId: number;
  content: string;
  createdAt: string;
  likeCount: number;
  isLikedByCurrentUser: boolean;
  isDelete: boolean;
  realname: string;
  avatarUrl: string;
  children: CommentNode[];
}

export interface CreateCommentRequest {
  postId: number;
  parentId: number;
  userId: number;
  content: string;
}

export interface CreateCommentResponse {
  comment: CommentNode | undefined;
}

export interface GetCommentRequest {
  commentId: number;
}

export interface GetCommentResponse {
  comment: CommentNode | undefined;
}

export const SOCIALNETWORK_PACKAGE_NAME = "socialnetwork";

/** ===== SERVICE DEFINITION ===== */

export interface SocialNetworkServiceClient {
  /** Gửi lời mời kết bạn ( Người gửi ) */

  addFriend(request: AddFriendRequest, metadata?: Metadata): Observable<AddFriendResponse>;

  /** Xem tất cả lời mời kết bạn mà bản thân đã gửi ( Người gửi ) */

  getSentFriend(request: GetSentFriendRequest, metadata?: Metadata): Observable<GetSentFriendResponse>;

  /** Xem tất cả lời mời kết bạn của bản thân để accept ( Người nhận ) */

  getIncomingFriend(request: GetIncomingFriendRequest, metadata?: Metadata): Observable<GetIncomingFriendResponse>;

  /** Chấp nhận yêu cầu kết bạn ( Người nhận ) */

  acceptFriend(request: AcceptFriendRequest, metadata?: Metadata): Observable<AcceptFriendResponse>;

  /** Hủy yêu cầu kết bạn ( chỉ áp dụng khi pending ) ( xóa record ) ( Người nhận ) */

  rejectFriend(request: RejectFriendRequest, metadata?: Metadata): Observable<RejectFriendResponse>;

  /** Lấy danh sách bạn bè của bản thân */

  getAllFriend(request: GetAllFriendRequest, metadata?: Metadata): Observable<GetAllFriendResponse>;

  /** Xóa 1 bạn bè nhất định ( xóa record ) */

  unfriend(request: UnfriendRequest, metadata?: Metadata): Observable<UnfriendResponse>;

  /** Chặn bạn bè bất kì ( Blocking User ) */

  blockUser(request: BlockUserRequest, metadata?: Metadata): Observable<BlockUserResponse>;

  /** Xem bạn và 1 user bất kì có phải bạn bè hay không */

  canChat(request: CanChatRequest, metadata?: Metadata): Observable<CanChatResponse>;

  /** Lưu tin nhắn chat giữa 2 người */

  saveMessage(request: SaveMessageRequest, metadata?: Metadata): Observable<SaveMessageResponse>;

  /** Lấy lịch sử nhắn tin của 2 người */

  getMessage(request: GetMessageRequest, metadata?: Metadata): Observable<GetMessageResponse>;

  /** Tạo group */

  createGroup(request: CreateGroupRequest, metadata?: Metadata): Observable<CreateGroupResponse>;

  /** Add User vào group */

  addUserToGroup(request: AddUserToGroupRequest, metadata?: Metadata): Observable<AddUserToGroupResponse>;

  /** Check xem group có tồn tại và userId có tồn tại trong group hay không */

  checkGroupUser(request: CheckGroupUserRequest, metadata?: Metadata): Observable<CheckGroupUserResponse>;

  /** Xem all group mà bản thân đã vào */

  getAllGroup(request: GetAllGroupRequest, metadata?: Metadata): Observable<GetAllGroupResponse>;

  /** Tạo comment trong bài viết */

  createComment(request: CreateCommentRequest, metadata?: Metadata): Observable<CreateCommentResponse>;

  /** Lấy thông tin comment dựa trên commentId */

  getComment(request: GetCommentRequest, metadata?: Metadata): Observable<GetCommentResponse>;

  /** Lấy danh sách comment của bài viết ( Build cây Json trả về FE, Có like hay chưa theo User ) */

  getAllComment(request: GetAllCommentRequest, metadata?: Metadata): Observable<GetAllCommentResponse>;

  /** Chỉnh sửa comment */

  updateComment(request: UpdateCommentRequest, metadata?: Metadata): Observable<UpdateCommentResponse>;

  /** Xóa comment ( Soft Delete ) */

  deleteComment(request: DeleteCommentRequest, metadata?: Metadata): Observable<DeleteCommentResponse>;

  /** Like comment */

  likeComment(request: LikeCommentRequest, metadata?: Metadata): Observable<LikeCommentResponse>;

  /** Unlike comment */

  unlikeComment(request: UnlikeCommentRequest, metadata?: Metadata): Observable<UnlikeCommentResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface SocialNetworkServiceController {
  /** Gửi lời mời kết bạn ( Người gửi ) */

  addFriend(request: AddFriendRequest, metadata?: Metadata): Observable<AddFriendResponse>;

  /** Xem tất cả lời mời kết bạn mà bản thân đã gửi ( Người gửi ) */

  getSentFriend(request: GetSentFriendRequest, metadata?: Metadata): Observable<GetSentFriendResponse>;

  /** Xem tất cả lời mời kết bạn của bản thân để accept ( Người nhận ) */

  getIncomingFriend(request: GetIncomingFriendRequest, metadata?: Metadata): Observable<GetIncomingFriendResponse>;

  /** Chấp nhận yêu cầu kết bạn ( Người nhận ) */

  acceptFriend(request: AcceptFriendRequest, metadata?: Metadata): Observable<AcceptFriendResponse>;

  /** Hủy yêu cầu kết bạn ( chỉ áp dụng khi pending ) ( xóa record ) ( Người nhận ) */

  rejectFriend(request: RejectFriendRequest, metadata?: Metadata): Observable<RejectFriendResponse>;

  /** Lấy danh sách bạn bè của bản thân */

  getAllFriend(request: GetAllFriendRequest, metadata?: Metadata): Observable<GetAllFriendResponse>;

  /** Xóa 1 bạn bè nhất định ( xóa record ) */

  unfriend(request: UnfriendRequest, metadata?: Metadata): Observable<UnfriendResponse>;

  /** Chặn bạn bè bất kì ( Blocking User ) */

  blockUser(request: BlockUserRequest, metadata?: Metadata): Observable<BlockUserResponse>;

  /** Xem bạn và 1 user bất kì có phải bạn bè hay không */

  canChat(request: CanChatRequest, metadata?: Metadata): Observable<CanChatResponse>;

  /** Lưu tin nhắn chat giữa 2 người */

  saveMessage(request: SaveMessageRequest, metadata?: Metadata): Observable<SaveMessageResponse>;

  /** Lấy lịch sử nhắn tin của 2 người */

  getMessage(request: GetMessageRequest, metadata?: Metadata): Observable<GetMessageResponse>;

  /** Tạo group */

  createGroup(request: CreateGroupRequest, metadata?: Metadata): Observable<CreateGroupResponse>;

  /** Add User vào group */

  addUserToGroup(request: AddUserToGroupRequest, metadata?: Metadata): Observable<AddUserToGroupResponse>;

  /** Check xem group có tồn tại và userId có tồn tại trong group hay không */

  checkGroupUser(request: CheckGroupUserRequest, metadata?: Metadata): Observable<CheckGroupUserResponse>;

  /** Xem all group mà bản thân đã vào */

  getAllGroup(request: GetAllGroupRequest, metadata?: Metadata): Observable<GetAllGroupResponse>;

  /** Tạo comment trong bài viết */

  createComment(request: CreateCommentRequest, metadata?: Metadata): Observable<CreateCommentResponse>;

  /** Lấy thông tin comment dựa trên commentId */

  getComment(request: GetCommentRequest, metadata?: Metadata): Observable<GetCommentResponse>;

  /** Lấy danh sách comment của bài viết ( Build cây Json trả về FE, Có like hay chưa theo User ) */

  getAllComment(request: GetAllCommentRequest, metadata?: Metadata): Observable<GetAllCommentResponse>;

  /** Chỉnh sửa comment */

  updateComment(request: UpdateCommentRequest, metadata?: Metadata): Observable<UpdateCommentResponse>;

  /** Xóa comment ( Soft Delete ) */

  deleteComment(request: DeleteCommentRequest, metadata?: Metadata): Observable<DeleteCommentResponse>;

  /** Like comment */

  likeComment(request: LikeCommentRequest, metadata?: Metadata): Observable<LikeCommentResponse>;

  /** Unlike comment */

  unlikeComment(request: UnlikeCommentRequest, metadata?: Metadata): Observable<UnlikeCommentResponse>;
}

export function SocialNetworkServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "addFriend",
      "getSentFriend",
      "getIncomingFriend",
      "acceptFriend",
      "rejectFriend",
      "getAllFriend",
      "unfriend",
      "blockUser",
      "canChat",
      "saveMessage",
      "getMessage",
      "createGroup",
      "addUserToGroup",
      "checkGroupUser",
      "getAllGroup",
      "createComment",
      "getComment",
      "getAllComment",
      "updateComment",
      "deleteComment",
      "likeComment",
      "unlikeComment",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SocialNetworkService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SocialNetworkService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SOCIAL_NETWORK_SERVICE_NAME = "SocialNetworkService";
